-- ============================================================================
-- Wodouh — all 9 migrations, in order, as one paste.
--
-- GENERATED by tools/make-sql-paste.mjs from supabase/migrations/.
-- Do not edit this file; edit a migration and regenerate.
--
-- FOR THE SUPABASE SQL EDITOR. Use this when you cannot run
-- `supabase db push` — no CLI, no database password, no terminal.
-- Dashboard -> SQL Editor -> paste -> Run.
--
-- IT RECORDS ITSELF. The block at the end writes the versions into
-- supabase_migrations.schema_migrations, the table the CLI reads to decide
-- what still needs applying. Without it, a later `supabase db push` would see
-- unapplied migrations and try to run them all again against a schema that
-- already has the tables. With it, the CLI and the dashboard agree.
--
-- RUN IT ONCE. It is NOT idempotent: 0001 creates tables without IF NOT
-- EXISTS, so a second run stops at `relation "profiles" already exists`.
-- Verified by running it twice rather than assuming.
--
-- A SECOND RUN IS HARMLESS ANYWAY, which is why the whole thing is wrapped in
-- BEGIN/COMMIT. The error aborts the transaction, COMMIT never happens, and
-- nothing from that run is applied. An error message and an unchanged
-- database, not a half-applied one.
--
-- IT DOES MAKE YOU AN OPERATOR, if your address is in public.admin_allowlist
-- (0008). The trigger there promotes an allowlisted, CONFIRMED email on first
-- sign-in, and also promotes anyone already signed in — so this is correct
-- whichever order those happen in.
-- ============================================================================

begin;

-- ===================================================================
-- 0001_init.sql
-- ===================================================================
-- Wodouh — initial schema.
--
-- Design constraint that drives this whole file: the product promises "your
-- contract never leaves your device". Nothing here stores contract text, PDF
-- bytes, or extracted clause quotes. We persist the *outcome* of an analysis
-- (a score, which rule ids fired, a verdict key) and the artefacts the user
-- explicitly authors. Analysis stays client-side.
--
-- Every table is keyed by auth.uid() and protected by RLS. There is no
-- service-role read path in the app; only Edge Functions use the service key.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- profiles
-- Minimum viable identity. No name, no phone, no address: we ask for nothing
-- we do not use. Email already lives in auth.users; we do not duplicate it.
create table public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  lang         text not null default 'ar' check (lang in ('ar','en')),
  theme        text not null default 'system' check (theme in ('system','light','dark')),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.profiles is
  'Per-user preferences. Deliberately holds no PII beyond the auth.users link.';

-- ------------------------------------------------------------- analyses
-- The result of a contract review. `doc_kind` is an i18n key (doc_emp,
-- doc_rent, doc_free, doc_pasted, ...), not free text. `rule_ids` records
-- which heuristics fired so history can be re-rendered in either language
-- without storing any of the user's own words.
create table public.analyses (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  doc_kind    text not null,
  score       smallint not null check (score between 0 and 100),
  signed_mode boolean not null default false,
  rule_ids    text[] not null default '{}',
  verdict_key text,
  created_at  timestamptz not null default now()
);

comment on column public.analyses.rule_ids is
  'Heuristic rule identifiers that matched. Never the matched text itself.';

-- --------------------------------------------------------------- letters
-- A negotiation letter the user chose to save. Body is authored by the user
-- (assembled from our templates and editable), so it is theirs to store.
create table public.letters (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  analysis_id uuid references public.analyses(id) on delete set null,
  title       text not null default '',
  body        text not null default '',
  lang        text not null default 'ar' check (lang in ('ar','en')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint letters_body_len check (char_length(body) <= 20000),
  constraint letters_title_len check (char_length(title) <= 200)
);

-- ------------------------------------------------------------ case_files
-- End-of-service / termination claim workspace. Amounts are the user's own
-- figures, entered by hand in the calculator.
create table public.case_files (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  reason        text,
  last_wage     numeric(12,2) check (last_wage is null or last_wage >= 0),
  start_date    date,
  end_date      date,
  unused_leave  smallint check (unused_leave is null or unused_leave between 0 and 365),
  claim_total   numeric(12,2) check (claim_total is null or claim_total >= 0),
  docs_ready    text[] not null default '{}',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint case_dates_ordered check (start_date is null or end_date is null or start_date <= end_date)
);

-- ------------------------------------------------------------- reminders
-- Contract deadlines. These are what Phase 5 exports to Apple/Google Calendar.
create table public.reminders (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  analysis_id uuid references public.analyses(id) on delete cascade,
  doc_kind    text not null,
  event_key   text not null,
  due_at      timestamptz not null,
  kind        text not null default 'info' check (kind in ('info','action','deadline')),
  rrule       text,
  done        boolean not null default false,
  created_at  timestamptz not null default now()
);

comment on column public.reminders.rrule is
  'RFC 5545 RRULE for recurring deadlines, e.g. annual leave accrual. Null = one-off.';

-- ------------------------------------------------------------------ RLS
alter table public.profiles   enable row level security;
alter table public.analyses   enable row level security;
alter table public.letters    enable row level security;
alter table public.case_files enable row level security;
alter table public.reminders  enable row level security;

-- profiles: a user sees and edits exactly one row — their own. No delete:
-- account deletion cascades from auth.users.
create policy profiles_select on public.profiles
  for select using ((select auth.uid()) = id);
create policy profiles_insert on public.profiles
  for insert with check ((select auth.uid()) = id);
create policy profiles_update on public.profiles
  for update using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

-- The owner-only pattern below is identical for the four data tables. The
-- with-check on update is what stops a user reassigning a row to someone else.
create policy analyses_select on public.analyses
  for select using ((select auth.uid()) = user_id);
create policy analyses_insert on public.analyses
  for insert with check ((select auth.uid()) = user_id);
create policy analyses_update on public.analyses
  for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy analyses_delete on public.analyses
  for delete using ((select auth.uid()) = user_id);

create policy letters_select on public.letters
  for select using ((select auth.uid()) = user_id);
create policy letters_insert on public.letters
  for insert with check ((select auth.uid()) = user_id);
create policy letters_update on public.letters
  for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy letters_delete on public.letters
  for delete using ((select auth.uid()) = user_id);

create policy case_files_select on public.case_files
  for select using ((select auth.uid()) = user_id);
create policy case_files_insert on public.case_files
  for insert with check ((select auth.uid()) = user_id);
create policy case_files_update on public.case_files
  for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy case_files_delete on public.case_files
  for delete using ((select auth.uid()) = user_id);

create policy reminders_select on public.reminders
  for select using ((select auth.uid()) = user_id);
create policy reminders_insert on public.reminders
  for insert with check ((select auth.uid()) = user_id);
create policy reminders_update on public.reminders
  for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy reminders_delete on public.reminders
  for delete using ((select auth.uid()) = user_id);

-- ---------------------------------------------------------------- indexes
-- Every query the app makes is "my rows, newest first", so each index leads
-- with user_id. RLS filters on user_id too, so these serve both.
create index analyses_user_created_idx   on public.analyses   (user_id, created_at desc);
create index letters_user_created_idx    on public.letters    (user_id, created_at desc);
create index case_files_user_created_idx on public.case_files (user_id, created_at desc);
create index reminders_user_due_idx      on public.reminders  (user_id, due_at)
  where done = false;

-- ------------------------------------------------------------- triggers
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch   before update on public.profiles
  for each row execute function public.touch_updated_at();
create trigger letters_touch    before update on public.letters
  for each row execute function public.touch_updated_at();
create trigger case_files_touch before update on public.case_files
  for each row execute function public.touch_updated_at();

-- A profile row must exist the moment a user signs up, whichever provider
-- they used. security definer because the new user has no session yet.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ===================================================================
-- 0002_integrations.sql
-- ===================================================================
-- Wodouh — commerce platform integrations (Zid, Salla, and whatever follows).
--
-- The consumer app does not read these tables. They exist so a business
-- account can connect a store and have Wodouh review the contracts and
-- documents that flow through it.
--
-- Security posture: OAuth tokens are secrets. They are written and read only
-- by Edge Functions using the service role, never by the browser. The RLS
-- policies below therefore expose *connection metadata* to the owner (so the
-- UI can say "connected to Salla, 3 days ago") while the tokens themselves
-- live in a separate table with no anon-accessible policy at all.

-- ------------------------------------------------------------ providers
-- A row per supported platform. Adding a platform is an insert plus an
-- adapter file, not a schema change — that is the modularity requirement.
create table public.integration_providers (
  id          text primary key,              -- 'zid' | 'salla' | ...
  name        text not null,
  auth_kind   text not null default 'oauth2' check (auth_kind in ('oauth2','api_key')),
  enabled     boolean not null default true,
  created_at  timestamptz not null default now()
);

insert into public.integration_providers (id, name) values
  ('zid',   'Zid'),
  ('salla', 'Salla')
on conflict (id) do nothing;

-- Public read: the UI needs to list what can be connected. Nothing secret here.
alter table public.integration_providers enable row level security;
create policy providers_read on public.integration_providers
  for select using (enabled);

-- ---------------------------------------------------------- connections
-- Owner-visible metadata about a store connection.
create table public.integration_connections (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  provider_id   text not null references public.integration_providers(id),
  external_id   text,                        -- merchant/store id on their side
  store_name    text,
  scopes        text[] not null default '{}',
  status        text not null default 'pending'
                check (status in ('pending','active','revoked','error')),
  last_sync_at  timestamptz,
  last_error    text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (user_id, provider_id, external_id)
);

alter table public.integration_connections enable row level security;

-- The owner may see and disconnect. They may not write tokens or flip status
-- to 'active' by hand — inserts and status transitions are done by the Edge
-- Function under the service role, which bypasses RLS.
create policy connections_select on public.integration_connections
  for select using ((select auth.uid()) = user_id);
create policy connections_delete on public.integration_connections
  for delete using ((select auth.uid()) = user_id);

-- --------------------------------------------------------------- secrets
-- Deliberately has RLS enabled and NO policies. With RLS on and no policy,
-- anon and authenticated roles can do nothing at all; only the service role
-- (which bypasses RLS) can touch it. This is the whole point: an access
-- token must never be reachable from a browser session, even the owner's.
create table public.integration_secrets (
  connection_id  uuid primary key references public.integration_connections(id) on delete cascade,
  access_token   text not null,
  refresh_token  text,
  expires_at     timestamptz,
  updated_at     timestamptz not null default now()
);

alter table public.integration_secrets enable row level security;

revoke all on public.integration_secrets from anon, authenticated;

comment on table public.integration_secrets is
  'RLS enabled with no policies by design: service role only. Never expose to a client.';

-- -------------------------------------------------------- webhook events
-- Raw inbound webhooks, recorded before processing so a failed handler can be
-- replayed and a suspicious delivery can be audited.
create table public.integration_events (
  id             uuid primary key default gen_random_uuid(),
  connection_id  uuid references public.integration_connections(id) on delete cascade,
  provider_id    text not null references public.integration_providers(id),
  topic          text not null,
  external_event_id text,
  payload        jsonb not null default '{}'::jsonb,
  processed_at   timestamptz,
  error          text,
  received_at    timestamptz not null default now(),
  -- Replay protection: the same delivery id is never stored twice.
  unique (provider_id, external_event_id)
);

alter table public.integration_events enable row level security;

-- Owners may read their own event history for transparency; only the service
-- role writes.
create policy events_select on public.integration_events
  for select using (
    exists (select 1 from public.integration_connections c
             where c.id = integration_events.connection_id
               and c.user_id = (select auth.uid()))
  );

create index events_conn_received_idx on public.integration_events (connection_id, received_at desc);
create index events_unprocessed_idx   on public.integration_events (received_at)
  where processed_at is null;

-- ------------------------------------------------------------ rate limit
-- Counter table backing the Edge Function limiter. Keyed by an opaque bucket
-- (user id, or a hash of the caller IP for unauthenticated routes) so we
-- never store raw addresses.
create table public.rate_limits (
  bucket      text not null,
  window_start timestamptz not null,
  count       integer not null default 0,
  primary key (bucket, window_start)
);

alter table public.rate_limits enable row level security;
revoke all on public.rate_limits from anon, authenticated;

create or replace function public.bump_rate_limit(p_bucket text, p_limit int, p_window interval)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  w timestamptz := date_trunc('second', now()) - (extract(epoch from now())::bigint % extract(epoch from p_window)::bigint) * interval '1 second';
  c int;
begin
  insert into public.rate_limits (bucket, window_start, count)
  values (p_bucket, w, 1)
  on conflict (bucket, window_start)
    do update set count = public.rate_limits.count + 1
  returning count into c;
  return c <= p_limit;   -- false once the caller is over budget
end;
$$;

comment on function public.bump_rate_limit is
  'Fixed-window counter. Returns false when the caller has exceeded p_limit in the current window.';

create trigger connections_touch before update on public.integration_connections
  for each row execute function public.touch_updated_at();

-- ===================================================================
-- 0003_accounts.sql
-- ===================================================================
-- Wodouh — accounts, identity, and stored contracts.
--
-- WHY THIS EXTENDS `profiles` INSTEAD OF ADDING A `users` TABLE
--
-- The spec this implements asked for a `users` table holding id, full_name,
-- email, phone, consent, provider. Every one of those either already exists in
-- auth.users or belongs beside the preferences already in public.profiles. A
-- second table keyed on the same uuid would be two rows to keep in step, two
-- RLS surfaces, and two places for an email to go stale. So the columns land
-- on `profiles`, which 0001 already created, already protects, and already
-- populates by trigger.
--
-- WHAT CHANGED ABOUT THE PRIVACY POSITION, STATED PLAINLY
--
-- 0001 opens: "Nothing here stores contract text, PDF bytes, or extracted
-- clause quotes." THAT REMAINS TRUE and every table below keeps it.
--
-- What is new is `contracts.original_filename`, and it deserves naming rather
-- than burying. A Saudi filename routinely carries the person's name and their
-- employer's — عقد-عبدالإله-أرامكو.pdf — so this column is personal data about
-- two parties, one of whom never agreed to anything. It is stored because the
-- product owner decided a recognisable list is worth it, which is a legitimate
-- call. What makes it defensible is that the reader can edit or clear it
-- (`contracts_update`), delete the row outright (`contracts_delete`), and that
-- it is the ONLY free text about a document anywhere in this schema.
--
-- CONSENT IS RECORDED, NOT ASSUMED
--
-- phone_marketing_consent defaults to false and is a separate column from the
-- phone number itself, so storing a number never implies permission to market
-- to it. Alongside it: WHEN consent was given and THE EXACT WORDING shown at
-- the time. A boolean alone cannot answer "what did they agree to?" a year
-- later, and that is the question that actually gets asked.
--
-- PDPL: this file stores Saudi personal data including a phone number and a
-- marketing flag. Region choice, retention and the data-subject rights in the
-- Personal Data Protection Law are not settled by any code here. Get advice
-- before the first real user.

-- ------------------------------------------------------------- identity
-- From the OAuth provider, written by the trigger below. Nullable throughout:
-- a provider may withhold any of them, and a missing name must never block a
-- sign-in.
alter table public.profiles
  add column if not exists full_name     text,
  add column if not exists email         text,
  add column if not exists avatar_url    text,
  add column if not exists auth_provider text
    check (auth_provider is null or auth_provider in ('google','apple'));

comment on column public.profiles.email is
  'Mirrored from auth.users at sign-up for convenience. auth.users is the source of truth.';

-- --------------------------------------------------------------- phone
-- Reference data only. No OTP, no verification, and NOTHING in the sign-in
-- path reads it — a phone number here can never be used to authenticate, which
-- is what keeps a wrong or recycled number from becoming an account takeover.
alter table public.profiles
  add column if not exists phone_number text
    check (phone_number is null or phone_number ~ '^\+?[0-9 ()-]{7,20}$'),
  add column if not exists phone_marketing_consent boolean not null default false,
  add column if not exists phone_consent_at timestamptz,
  add column if not exists phone_consent_text text,
  -- Asked once. This records that the question was put, whatever the answer,
  -- so a reader who skipped is not asked again on every visit.
  add column if not exists phone_prompted_at timestamptz;

comment on column public.profiles.phone_number is
  'Reference only. Never used for authentication, verification, or account recovery.';
comment on column public.profiles.phone_consent_text is
  'The exact sentence shown when consent was given. A boolean cannot answer "what did they agree to?".';

-- Consent cannot be true without a record of when it was given and what was
-- shown. This is the constraint that stops a future code path from flipping
-- the flag silently.
alter table public.profiles
  drop constraint if exists profiles_consent_recorded;
alter table public.profiles
  add constraint profiles_consent_recorded check (
    phone_marketing_consent = false
    or (phone_consent_at is not null and phone_consent_text is not null)
  );

-- ----------------------------------------------------------- contracts
-- A document the reader chose to keep a record of. The document itself is not
-- here: no bytes, no text, no quotes. This row is a label and a status.
create table if not exists public.contracts (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  original_filename text,
  language          text not null default 'ar' check (language in ('ar','en')),
  status            text not null default 'uploaded'
    check (status in ('uploaded','analyzed','archived')),
  uploaded_at       timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint contracts_filename_len check (
    original_filename is null or char_length(original_filename) <= 255)
);

comment on table public.contracts is
  'A record that a document was reviewed. Never the document.';

-- --------------------------------------------------- contract_analyses
-- The outcome of a review. red_flags and negotiation_points are jsonb because
-- their shape is the app''s, not the database''s — but they must stay
-- REFERENCES to findings (rule ids, keys, scores), never the reader''s clause
-- text. The size ceiling below is the crude guard against that: quoted
-- contract text does not fit in 16 KB, findings do.
create table if not exists public.contract_analyses (
  id                 uuid primary key default gen_random_uuid(),
  contract_id        uuid not null references public.contracts(id) on delete cascade,
  user_id            uuid not null references auth.users(id) on delete cascade,
  score              smallint not null check (score between 0 and 100),
  verdict_summary    text,
  red_flags          jsonb not null default '[]'::jsonb,
  negotiation_points jsonb not null default '[]'::jsonb,
  created_at         timestamptz not null default now(),
  constraint analyses_verdict_len check (
    verdict_summary is null or char_length(verdict_summary) <= 2000),
  constraint analyses_flags_shape check (
    jsonb_typeof(red_flags) = 'array' and jsonb_typeof(negotiation_points) = 'array'),
  constraint analyses_flags_size check (
    pg_column_size(red_flags) + pg_column_size(negotiation_points) <= 16384)
);

-- user_id is carried here as well as on contracts. It is redundant by design:
-- it lets RLS decide ownership without a join, so a policy cannot be defeated
-- by a subquery that the planner rewrites. The trigger below keeps it honest.
comment on column public.contract_analyses.user_id is
  'Denormalised from contracts so RLS never needs a join. Enforced by trigger.';

create or replace function public.contract_analysis_owner()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare owner uuid;
begin
  select c.user_id into owner from public.contracts c where c.id = new.contract_id;
  if owner is null then
    raise exception 'contract % not found', new.contract_id;
  end if;
  -- The parent decides. A client that sends someone else's user_id is
  -- corrected rather than trusted.
  new.user_id := owner;
  return new;
end;
$$;

drop trigger if exists contract_analyses_owner on public.contract_analyses;
create trigger contract_analyses_owner
  before insert or update on public.contract_analyses
  for each row execute function public.contract_analysis_owner();

drop trigger if exists contracts_touch on public.contracts;
create trigger contracts_touch
  before update on public.contracts
  for each row execute function public.touch_updated_at();

-- ------------------------------------------------------------------ RLS
alter table public.contracts         enable row level security;
alter table public.contract_analyses enable row level security;

create policy contracts_select on public.contracts
  for select using ((select auth.uid()) = user_id);
create policy contracts_insert on public.contracts
  for insert with check ((select auth.uid()) = user_id);
create policy contracts_update on public.contracts
  for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy contracts_delete on public.contracts
  for delete using ((select auth.uid()) = user_id);

-- Same owner-only shape. The insert check additionally requires that the
-- parent contract is the caller''s, so an analysis cannot be attached to a
-- stranger''s contract even though the trigger would overwrite user_id.
create policy contract_analyses_select on public.contract_analyses
  for select using ((select auth.uid()) = user_id);
create policy contract_analyses_insert on public.contract_analyses
  for insert with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.contracts c
      where c.id = contract_id and c.user_id = (select auth.uid())));
create policy contract_analyses_update on public.contract_analyses
  for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy contract_analyses_delete on public.contract_analyses
  for delete using ((select auth.uid()) = user_id);

-- ---------------------------------------------------------------- indexes
create index if not exists contracts_user_idx
  on public.contracts (user_id, uploaded_at desc);
create index if not exists contract_analyses_user_idx
  on public.contract_analyses (user_id, created_at desc);
create index if not exists contract_analyses_contract_idx
  on public.contract_analyses (contract_id);

-- ------------------------------------------------- new-user profile fill
-- Replaces the 0001 version, which created an empty row. The provider hands us
-- a name, an email and an avatar at first sign-in and never again as reliably,
-- so they are captured now.
--
-- Apple is deliberately handled: it returns the full name ONLY on the very
-- first authorisation, and its "hide my email" relay address is a real address
-- that must be stored as given. Both are read from raw_user_meta_data with
-- fallbacks rather than assumed present.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  meta jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  prov text := nullif(new.raw_app_meta_data ->> 'provider', '');
begin
  insert into public.profiles (id, full_name, email, avatar_url, auth_provider)
  values (
    new.id,
    nullif(coalesce(meta ->> 'full_name', meta ->> 'name', ''), ''),
    nullif(coalesce(new.email, meta ->> 'email', ''), ''),
    nullif(coalesce(meta ->> 'avatar_url', meta ->> 'picture', ''), ''),
    case when prov in ('google','apple') then prov end
  )
  on conflict (id) do update set
    -- Never overwrite something already there with a null on a later sign-in:
    -- Apple gives the name once, and a second sign-in would erase it.
    full_name     = coalesce(public.profiles.full_name, excluded.full_name),
    email         = coalesce(excluded.email, public.profiles.email),
    avatar_url    = coalesce(excluded.avatar_url, public.profiles.avatar_url),
    auth_provider = coalesce(public.profiles.auth_provider, excluded.auth_provider);
  return new;
end;
$$;

-- --------------------------------------------------------- account erasure
-- PDPL gives a data subject the right to have their data deleted, and "email
-- support and wait" is not an implementation of it. Deleting the auth user
-- cascades to every table above; this is the callable, auditable version.
create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare uid uuid := (select auth.uid());
begin
  if uid is null then
    raise exception 'not signed in';
  end if;
  delete from auth.users where id = uid;
end;
$$;

revoke all on function public.delete_my_account() from public;
grant execute on function public.delete_my_account() to authenticated;

-- ===================================================================
-- 0004_uploads.sql
-- ===================================================================
-- Wodouh — uploaded files, and who owns them.
--
-- WHY THIS TABLE EXISTS AT ALL
--
-- Anthropic's Files API returns a file_id that is WORKSPACE-scoped, not
-- user-scoped. Every file_id our API key ever created is readable by our API
-- key. So a file_id is not a capability and must never be treated as one: a
-- client that sends us `file_id: "file_abc"` is making a claim about ownership,
-- not proving it, and a signed-in user guessing or replaying another user's id
-- would read a stranger's employment contract.
--
-- This table is the proof. The server records who uploaded what at the moment
-- it uploads, and every later request looks the id up HERE, scoped to the
-- caller, before it goes anywhere near Anthropic. The client never sends a
-- file_id and is never shown one.
--
-- WHEN THIS PATH IS USED, WHICH IS NOT OFTEN
--
-- Text-based PDFs are extracted on the reader's own device and only the TEXT is
-- sent for analysis — no file is uploaded and nothing lands here. This table
-- serves the one case on-device code cannot handle: a scan or a photograph,
-- which has no text layer at all. That upload is an explicit, separate opt-in,
-- because it is the only flow in Wodouh where the document itself leaves the
-- phone.
--
-- RETENTION IS AN OBLIGATION, NOT AN INTENTION
--
-- A file uploaded to Anthropic persists until it is explicitly deleted. The
-- delete call can fail, and a function can time out between upload and delete,
-- so "we delete it immediately" is only true if something notices when it did
-- not happen. deleted_at plus expires_at is what makes the sweep possible:
-- anything past expires_at with deleted_at still null is a file that outlived
-- its purpose and needs removing.
--
-- PDPL: this records that a Saudi resident's identity document or employment
-- contract was transmitted to a processor outside the Kingdom. Retention,
-- cross-border transfer and the data subject's rights are not settled by any
-- code here. Get advice before the first real user.

create table if not exists public.uploads (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  -- The Anthropic file_id. Written by the server only, never accepted from a
  -- client, never returned to one.
  file_id      text not null,
  purpose      text not null default 'contract_scan'
    check (purpose in ('contract_scan')),
  byte_size    integer check (byte_size is null or byte_size between 0 and 33554432),
  mime_type    text,
  created_at   timestamptz not null default now(),
  -- Short by design. A scan is uploaded, read once, and deleted; an hour is
  -- generous for a retry and far short of anything resembling storage.
  expires_at   timestamptz not null default now() + interval '1 hour',
  deleted_at   timestamptz,
  constraint uploads_file_id_unique unique (file_id)
);

comment on table public.uploads is
  'Which user owns which Anthropic file_id. A file_id from a client is a claim, not a proof — this table is the proof.';
comment on column public.uploads.deleted_at is
  'Set when the file has actually been deleted upstream. Null past expires_at means the delete did not happen and the sweep must retry.';

create index if not exists uploads_user_idx on public.uploads (user_id, created_at desc);
-- The sweep's query: everything expired that was never confirmed deleted.
create index if not exists uploads_sweep_idx on public.uploads (expires_at)
  where deleted_at is null;

-- ------------------------------------------------------------------ RLS
-- Enabled with NO policies, and rights revoked from both client roles. This is
-- the strictest configuration available: only the service role, inside an Edge
-- Function, can read or write it. The same pattern 0002 uses for
-- integration_secrets, and for the same reason — a reader has no legitimate
-- need to see a file_id, and the one thing that must never happen is a client
-- learning an identifier it could replay.
alter table public.uploads enable row level security;
revoke all on public.uploads from anon, authenticated;

-- --------------------------------------------------------------- the sweep
-- Called by the Edge Function on a schedule. Returns what still needs deleting
-- upstream; the function does the delete and then marks the row.
create or replace function public.uploads_pending_delete(max_rows integer default 100)
returns table (id uuid, file_id text)
language sql
security definer
set search_path = ''
as $$
  select u.id, u.file_id
  from public.uploads u
  where u.deleted_at is null and u.expires_at < now()
  order by u.expires_at
  limit least(greatest(coalesce(max_rows, 100), 1), 1000);
$$;

revoke all on function public.uploads_pending_delete(integer) from public, anon, authenticated;

-- ===================================================================
-- 0005_admin.sql
-- ===================================================================
-- Wodouh — the founder console: who may operate it, what it can switch, and
-- an unforgeable record of every switch that moved.
--
-- WHY THIS TABLE SET EXISTS
--
-- Every feature switch in Wodouh is a constant compiled into app/index.html:
-- PAYMENT_LIVE, SUBSCRIPTIONS_LIVE, LAWYER_DESK.live, WODOUH_LAUNCHED. Changing
-- one means an edit, a test run, a push and a Pages deploy. That is a good
-- default and a bad emergency procedure — when payments are misbehaving in
-- front of real people, "wait for a deploy" is not an answer.
--
-- So the switches move here, and the app asks. That trade is real and it is
-- recorded rather than glossed:
--
--   WHAT IS GAINED   a flag can be turned off in seconds, from a phone.
--   WHAT IS PAID     the app now makes a network request it did not make
--                    before. app/index.html fetches LAZILY — only when a
--                    reader first reaches a surface a flag governs — so
--                    someone who only uses the free calculator still makes no
--                    request at all. The privacy copy says so in both
--                    languages. If that ever stops being true, the copy is
--                    wrong and this comment is the reason it must be fixed.
--
-- FAILURE FALLS TO THE SAFE SIDE, ALWAYS
--
-- A flag row that is missing, unreadable, or stale reads as OFF, because the
-- app falls back to the compiled-in constant and every one of those is false.
-- An attacker who could make this table unreachable could turn features off.
-- They could not turn one on, and that asymmetry is deliberate.
--
-- THE AUDIT LOG CANNOT BE WRITTEN BY A CLIENT
--
-- flag_audit has a SELECT policy and no other policy, so under row level
-- security every insert, update and delete from a browser is denied. The only
-- thing that writes it is the trigger below, which runs inside the database on
-- the way through. "Who turned payments on at 2am" is therefore a question with
-- an answer that the person who did it could not have edited.
--
-- PDPL: nothing here is a data subject's personal data beyond the operator's
-- own auth.users id.

-- ------------------------------------------------------------- operators
-- Membership is granted BY HAND in the Supabase dashboard, deliberately. There
-- is no client-facing write policy below, so nothing reachable from a browser
-- can add an operator — including the console itself. Making yourself an admin
-- requires the database, which requires the project owner.
create table if not exists public.admins (
  user_id  uuid primary key references auth.users(id) on delete cascade,
  -- owner may move a switch; viewer may only look. Two roles, because a third
  -- would be a permission system nobody asked for.
  role     text not null default 'viewer' check (role in ('owner', 'viewer')),
  added_at timestamptz not null default now(),
  note     text check (note is null or length(note) <= 200)
);

comment on table public.admins is
  'Who may open the founder console. Granted by hand in the dashboard; no client write policy exists.';

alter table public.admins enable row level security;

-- An operator may confirm their own membership, and learns nothing about any
-- other operator. Absent any other policy, RLS denies every write from a
-- client — which is the point.
create policy admins_select_self on public.admins
  for select using ((select auth.uid()) = user_id);

-- SECURITY DEFINER so it can see rows the caller's own policy hides, and
-- search_path pinned to '' so a caller cannot shadow public.admins with a
-- table of their own and answer the question themselves.
create or replace function public.is_admin(want text default 'viewer')
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admins a
     where a.user_id = (select auth.uid())
       and (want = 'viewer' or a.role = 'owner')
  );
$$;

revoke all on function public.is_admin(text) from public;
-- anon as well as authenticated, and this was found by RUNNING it. Granting
-- only to authenticated meant a signed-out request that touched any policy
-- calling this — a stray read of flag_audit, an update attempt on app_flags —
-- failed with "permission denied for function is_admin" instead of quietly
-- returning nothing. Denial is correct in both cases; a loud error that names
-- an internal function is a worse way to say it, and it makes a routine denial
-- look like an outage. Nothing leaks: for a signed-out caller auth.uid() is
-- null, so this returns false and says only that.
grant execute on function public.is_admin(text) to anon, authenticated;

-- ---------------------------------------------------------------- flags
-- WORLD-READABLE ON PURPOSE. Every reader's app needs to know whether payments
-- are live, and they are not signed in. There is nothing here to protect: the
-- contents are exactly what the app's own behaviour reveals within one tap.
--
-- The KEY SET IS FIXED BY THE CODE THAT READS IT. There is no insert or delete
-- policy, so the console can flip a flag and can never invent one. A key the
-- app does not know would do nothing anyway, and a key the app DOES know that
-- someone deleted would read as off — this way neither can happen by accident.
create table if not exists public.app_flags (
  key        text primary key check (key ~ '^[a-z][a-z0-9_]{2,40}$'),
  enabled    boolean not null default false,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  note       text check (note is null or length(note) <= 280)
);

comment on table public.app_flags is
  'Runtime feature switches. Public read; only an owner may change one. A missing or unreadable row reads as OFF in the app.';
comment on column public.app_flags.enabled is
  'The app never trusts this to turn a feature ON without its credential also being present — see the dependency guard in admin/admin.js.';

alter table public.app_flags enable row level security;

create policy app_flags_select on public.app_flags
  for select using (true);

-- The with-check matters as much as the using: without it an owner could pass
-- the row-level test on the way in and write something the policy would not
-- have allowed on the way out.
create policy app_flags_update on public.app_flags
  for update using (public.is_admin('owner'))
  with check (public.is_admin('owner'));

-- The five switches the app reads, all off. Seeding them here rather than
-- letting the console create them is what keeps the key set a property of the
-- code rather than of whoever clicked last.
insert into public.app_flags (key, enabled, note) values
  ('launched',      false, 'The pre-launch curtain. False sends visitors to the coming-soon page.'),
  ('payments',      false, 'Card payment. Turning this on charges real people.'),
  ('subscriptions', false, 'Recurring plans on the account screen.'),
  ('ai_analysis',   false, 'Sends contract text off the device. Needs ANALYZE_URL configured too.'),
  ('lawyer_desk',   false, 'The lawyer handoff. Needs an actual arrangement with a lawyer.')
on conflict (key) do nothing;

-- ----------------------------------------------------------- the record
-- Append-only from every direction a client can reach. One SELECT policy and
-- nothing else: RLS denies what it does not permit, so a browser cannot insert
-- a false entry, amend a true one, or delete the one it wishes had not
-- happened.
create table if not exists public.flag_audit (
  id           bigint generated always as identity primary key,
  key          text not null,
  from_enabled boolean,
  to_enabled   boolean not null,
  changed_at   timestamptz not null default now(),
  changed_by   uuid references auth.users(id) on delete set null,
  note         text
);

comment on table public.flag_audit is
  'Every flag change, written only by the trigger below. No client can write, amend or delete a row here.';

alter table public.flag_audit enable row level security;

create policy flag_audit_select on public.flag_audit
  for select using (public.is_admin('viewer') and (select auth.uid()) is not null);

-- Stamps the row and records the change in one place, so "who changed it" and
-- "when" cannot disagree with the log. SECURITY DEFINER because flag_audit
-- has no insert policy — not even for an owner — and this is the only writer.
create or replace function public.log_flag_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at := now();
  new.updated_by := (select auth.uid());
  /* The key is immutable: a rename would orphan the audit trail from the
     switch it describes. */
  new.key := old.key;

  if new.enabled is distinct from old.enabled then
    insert into public.flag_audit (key, from_enabled, to_enabled, changed_by, note)
    values (old.key, old.enabled, new.enabled, (select auth.uid()), new.note);
  end if;
  return new;
end;
$$;

drop trigger if exists app_flags_audit on public.app_flags;
create trigger app_flags_audit
  before update on public.app_flags
  for each row execute function public.log_flag_change();

-- ===================================================================
-- 0006_function_grants.sql
-- ===================================================================
-- Wodouh — take back the EXECUTE grants that Supabase hands out by default.
--
-- WHY THIS FILE EXISTS, AND WHY THE EARLIER REVOKES DID NOT WORK
--
-- 0003 ends with `revoke all on function public.delete_my_account() from
-- public;` followed by a grant to authenticated. That reads as "only signed-in
-- callers may run this". It is not what happened. Checked against the real
-- project after the migrations were applied:
--
--   delete_my_account   anon => TRUE
--
-- Supabase's default privileges grant EXECUTE on every new function in the
-- public schema to `anon` and `authenticated` as roles in their own right.
-- Revoking from PUBLIC removes the PUBLIC grant and leaves those two
-- untouched. So a revoke that names only PUBLIC changes nothing a client can
-- reach, while looking in the source exactly like a revoke that does.
--
-- 0004 got this right by accident of thoroughness — it names all three roles,
-- and uploads_pending_delete is correspondingly unreachable. That contrast is
-- the whole lesson: name the roles.
--
-- WHAT WAS ACTUALLY REACHABLE
--
-- Every SECURITY DEFINER function below was callable by an anonymous browser
-- over /rest/v1/rpc/. The one that matters is bump_rate_limit: it takes the
-- bucket as an argument, so anyone could inflate the counter for any bucket
-- they liked and push a chosen user over their limit. A rate limiter that a
-- stranger can drive is a denial-of-service tool pointed at your own readers.
--
-- The trigger functions (touch_updated_at, handle_new_user,
-- contract_analysis_owner, log_flag_change) would error if called directly,
-- having no trigger context — but "it happens to fail" is not access control,
-- and they have no business on the public API surface. Triggers execute as the
-- table owner and do not consult these grants, so revoking costs nothing.
--
-- WHAT IS DELIBERATELY LEFT ALONE
--
-- public.is_admin(text) keeps its grant to anon, for the reason 0005 records
-- at length: policies call it during signed-out requests, and without the
-- grant a routine denial surfaces as "permission denied for function
-- is_admin" instead of quietly returning nothing. It leaks nothing — for a
-- signed-out caller auth.uid() is null, so it returns false.
--
-- service_role holds its own EXECUTE grant, independent of these, so the Edge
-- Functions that call bump_rate_limit are unaffected. Verified before writing
-- this, not assumed.

-- The rate limiter: service_role only, like the table it writes.
revoke all on function public.bump_rate_limit(text, int, interval)
  from public, anon, authenticated;

-- Trigger functions. Triggers do not consult these grants.
revoke all on function public.touch_updated_at()          from public, anon, authenticated;
revoke all on function public.handle_new_user()           from public, anon, authenticated;
revoke all on function public.contract_analysis_owner()   from public, anon, authenticated;
revoke all on function public.log_flag_change()           from public, anon, authenticated;

-- Account erasure: what 0003 meant to say. A signed-in caller may delete their
-- own account and nobody else's; anon cannot reach it at all. The function's
-- own `if uid is null then raise` stays as the second line of defence.
revoke all on function public.delete_my_account() from public, anon, authenticated;
grant execute on function public.delete_my_account() to authenticated;

-- ===================================================================
-- 0007_blockers.sql
-- ===================================================================
-- Wodouh — what is blocking launch, moved out of the public bundle.
--
-- WHY THIS TABLE EXISTS
--
-- The founder console's blockers panel was a hardcoded array in
-- admin/admin.js. That file is served from GitHub Pages at a guessable URL,
-- so every row in it was world-readable by anyone who ran `curl`. One of them
-- read:
--
--   Lawyer review — "Every register row needs a licensed Saudi lawyer before
--                    real users"
--
-- On a product that gives Saudi employment-law guidance, that is a published
-- admission that the legal content is unreviewed. Beside it sat "the pay
-- button simulates" and "CI is unbilled". None of this is a security hole —
-- nothing there grants any capability — which is exactly why row level
-- security did not answer it. It is a liability disclosure, and the fix for a
-- disclosure is to stop publishing it.
--
-- WHY GATING THE RENDER WOULD HAVE BEEN THEATRE
--
-- Refusing to draw the panel changes nothing while the strings are still in a
-- file anyone can fetch. The console could have shown a padlock and the
-- sentence would still have been one `curl` away. The strings had to LEAVE THE
-- BUNDLE, which means living somewhere with an authorisation check in front of
-- them. That is this table.
--
-- WHAT IS DELIBERATELY NOT MOVED
--
-- The status panel above it stays public and uncredentialed. It derives
-- everything from /index.html, /app/index.html and docs/legal-sources.md —
-- all already public — so a stranger could compute it themselves. Hiding it
-- would buy nothing and would cost the one panel that works when the database
-- does not.

create table if not exists public.launch_blockers (
  key   text primary key check (key ~ '^[a-z][a-z0-9_]{2,40}$'),
  label text not null check (length(label) <= 80),
  -- The sentence that must not be public. Kept here rather than in the client
  -- for the reason this whole file exists.
  note  text not null check (length(note) <= 280),
  done  boolean not null default false,
  sort  smallint not null default 0
);

comment on table public.launch_blockers is
  'Founder launch checklist. Operator-only by policy: these rows describe what is NOT ready, which is not a public fact.';

alter table public.launch_blockers enable row level security;

-- Unlike app_flags, which is world-readable because every reader's app needs
-- to know whether payments are live, nothing outside this console has any use
-- for these rows. An operator sees them; everyone else gets an empty result
-- rather than an error, which is the difference between "nothing to show you"
-- and "something is here that you may not have".
-- drop-then-create rather than a bare create, so this file can be pasted into
-- the SQL editor twice without the second run failing on "policy already
-- exists". create policy has no IF NOT EXISTS in Postgres, and a paste that
-- errors the second time is a paste someone will assume did not work the
-- first. Found by running it twice against a database already at 0006, which
-- is the state the live project is in.
drop policy if exists launch_blockers_select on public.launch_blockers;
create policy launch_blockers_select on public.launch_blockers
  for select using (public.is_admin('viewer'));

-- with check as well as using, for the reason 0005 gives: without it an owner
-- could pass the test on the way in and write a row the policy would not have
-- allowed on the way out.
drop policy if exists launch_blockers_update on public.launch_blockers;
create policy launch_blockers_update on public.launch_blockers
  for update using (public.is_admin('owner'))
  with check (public.is_admin('owner'));

-- No insert or delete policy. The key set belongs to the code that reads it,
-- not to whoever clicked last — the same argument app_flags makes.

insert into public.launch_blockers (key, label, note, done, sort) values
  ('supabase_project', 'Supabase project',
   'Unblocks accounts, sync, the switches on this page, and the AI', false, 1),
  ('anthropic_key', 'Anthropic API key',
   'Set as a function secret, never in the browser. Unblocks Ask and the AI read', false, 2),
  ('payment_processor', 'Payment processor',
   'Unblocks charging. Until then the pay button simulates', false, 3),
  ('apple_signin', 'Apple Developer account',
   'Unblocks Apple sign-in. Google works without it', false, 4),
  ('actions_billing', 'GitHub Actions billing',
   'Unblocks CI and the live watchdog. Pages deploys either way', false, 5),
  ('lawyer_review', 'Lawyer review',
   'Every register row needs a licensed Saudi lawyer before real users', false, 6)
on conflict (key) do nothing;

-- ===================================================================
-- 0008_operator_allowlist.sql
-- ===================================================================
-- Wodouh — who may operate the console, decided before they first sign in.
--
-- THE PROBLEM THIS SOLVES
--
-- public.admins.user_id references auth.users(id), so a person cannot be made
-- an operator until they have signed in at least once and a row exists to
-- point at. That is a sound foreign key and an impossible starting position:
-- the console is the thing you sign in to, and until someone is an operator it
-- shows them nothing. Every operator so far had to be inserted by hand, from
-- outside the product, after their first sign-in.
--
-- An allowlist keyed by EMAIL can be written in advance, because an email is
-- not a foreign key to anything. The trigger below promotes a matching user
-- the moment their auth.users row appears.
--
-- WHY MATCHING ON EMAIL IS SAFE HERE, AND WHERE ITS LIMIT IS
--
-- The match requires a CONFIRMED email. For Google and Apple that means the
-- provider asserted it, which is the same assurance any "invite by email"
-- flow in any product relies on: to be promoted you must be able to sign in as
-- that address, which means controlling it. Someone who merely knows the
-- address gains nothing.
--
-- The limit worth naming: this is only as strong as the mailbox and the
-- identity provider behind it. If an allowlisted Google account is taken over,
-- the console goes with it. That is true of every admin system that has a
-- password reset, and it is the reason the allowlist is short and the roles
-- are two.
--
-- CASE AND WHITESPACE. Addresses are compared lowercased and trimmed, because
-- "Abdulelah@..." and "abdulelah@..." are the same mailbox and a checklist
-- that says otherwise fails in the least helpful way possible — silently, at
-- the moment someone needs to get in.
--
-- NO CLIENT MAY READ OR WRITE THIS. RLS is enabled with no policy at all, so
-- anon and authenticated can do nothing with it — the same configuration
-- 0002 uses for integration_secrets. The list of people who can operate your
-- product is not a public fact, and neither is the fact that a given address
-- is on it.

create table if not exists public.admin_allowlist (
  email    text primary key check (email = lower(btrim(email)) and email like '%@%'),
  role     text not null default 'owner' check (role in ('owner', 'viewer')),
  added_at timestamptz not null default now(),
  note     text check (note is null or length(note) <= 200)
);

comment on table public.admin_allowlist is
  'Emails that become operators on first sign-in. RLS on with no policies: service role only, never reachable from a browser.';

alter table public.admin_allowlist enable row level security;
revoke all on public.admin_allowlist from anon, authenticated;

insert into public.admin_allowlist (email, role, note) values
  ('abdulelah@alwodouh.com',    'owner', 'Founder'),
  ('crashbook2014@gmail.com',   'owner', 'Founder'),
  ('abdulelah-alshi@hotmail.com','owner', 'Founder')
on conflict (email) do nothing;

-- --------------------------------------------------------- the promotion
-- Runs on insert AND update of auth.users. Update matters: an OAuth user's
-- email_confirmed_at is often set microseconds after the row is created, so an
-- insert-only trigger would miss the very case it exists for.
create or replace function public.promote_allowlisted_admin()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  want text;
  addr text := lower(btrim(coalesce(new.email, '')));
begin
  if addr = '' or new.email_confirmed_at is null then
    return new;
  end if;

  select a.role into want
    from public.admin_allowlist a
   where a.email = addr;

  if want is null then
    return new;
  end if;

  -- do nothing on conflict: a role set by hand in the dashboard outranks the
  -- list, so re-signing in never silently demotes or promotes an existing
  -- operator.
  insert into public.admins (user_id, role, note)
  values (new.id, want, 'from admin_allowlist')
  on conflict (user_id) do nothing;

  return new;
end;
$$;

revoke all on function public.promote_allowlisted_admin()
  from public, anon, authenticated;

drop trigger if exists on_auth_user_allowlisted on auth.users;
create trigger on_auth_user_allowlisted
  after insert or update of email, email_confirmed_at on auth.users
  for each row execute function public.promote_allowlisted_admin();

-- Anyone already signed in who is on the list but not yet an operator. Makes
-- the migration correct whether it runs before or after the first sign-in,
-- which is the whole point of writing it as a table rather than as an INSERT
-- someone has to remember to run at the right moment.
insert into public.admins (user_id, role, note)
select u.id, a.role, 'from admin_allowlist'
  from auth.users u
  join public.admin_allowlist a on a.email = lower(btrim(u.email))
 where u.email_confirmed_at is not null
on conflict (user_id) do nothing;

-- ===================================================================
-- 0009_scans.sql
-- ===================================================================
-- Wodouh — the record of how many free scans an account has used.
--
-- WHAT THIS IS FOR
--
-- The free tier is one contract scan a month. That was counted in
-- localStorage, which meant clearing site data or opening a private window
-- reset it. Counting it against an account instead makes the limit survive
-- both.
--
-- WHAT IT DOES NOT DO, SAID PLAINLY
--
-- It does not ENFORCE anything, and describing it as enforcement would be
-- wrong. Wodouh analyses a contract on the reader's own device — that is the
-- product's central privacy promise — so no server is in a position to
-- withhold a scan. This table is a RECORD, and the app honours it.
--
-- That defeats clearing storage, private windows, and a second browser. It
-- does not defeat someone who edits the JavaScript to skip the insert. Real
-- enforcement would mean sending the contract to a server to be analysed,
-- which is the one thing this product promises never to do. The trade is
-- deliberate and the weaker guarantee is the correct one.
--
-- WHAT IS RECORDED, AND WHAT IS NOT
--
-- A user id and a timestamp. That is the whole row.
--
-- NOT the contract, its text, its filename, its length, its score, its
-- clauses, or what kind of document it was. Someone reading this table learns
-- that an account scanned something on a date, and nothing whatsoever about
-- what they scanned. The privacy policy says so in both languages, because
-- this is new personal data and appearing in a migration is not disclosure.
--
-- PDPL: a Saudi resident's activity timestamps, tied to an identity. Minimal,
-- but not nothing. Retention below is 13 months for the reason given.

create table if not exists public.scan_events (
  id         bigint generated always as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

comment on table public.scan_events is
  'One row per free scan: user id and time, nothing about the document. A record the app honours, not an enforcement mechanism — analysis is on-device.';

create index if not exists scan_events_user_month_idx
  on public.scan_events (user_id, created_at desc);

alter table public.scan_events enable row level security;

-- A reader may see and add their OWN rows, and nothing else. Insert is open to
-- the owner because the client is what knows a scan happened — the server
-- never sees the contract and could not infer it.
drop policy if exists scan_events_select on public.scan_events;
create policy scan_events_select on public.scan_events
  for select using ((select auth.uid()) = user_id);

drop policy if exists scan_events_insert on public.scan_events;
create policy scan_events_insert on public.scan_events
  for insert with check ((select auth.uid()) = user_id);

-- NO UPDATE OR DELETE POLICY, deliberately. A reader who could delete their
-- own rows would have a one-click reset of the very limit this table exists to
-- record, which would leave it doing nothing at all while looking like it did
-- something. Erasure still works: deleting the account cascades from
-- auth.users, which is the right granularity for a data-subject request.

-- --------------------------------------------------------------- retention
-- Thirteen months, so a "this month" question can always look one full year
-- back and still find the boundary. Older rows answer no question anyone asks.
create or replace function public.prune_scan_events()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare n integer;
begin
  delete from public.scan_events where created_at < now() - interval '13 months';
  get diagnostics n = row_count;
  return n;
end;
$$;

-- Named roles, not just PUBLIC: revoking from PUBLIC alone leaves Supabase's
-- default grants to anon and authenticated untouched, which is what 0006
-- exists to fix. Do not shorten this.
revoke all on function public.prune_scan_events() from public, anon, authenticated;

-- ============================================================================
-- Bookkeeping: tell the CLI these are applied, so it never re-runs them.
-- ============================================================================
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version text primary key,
  statements text[],
  name text
);
insert into supabase_migrations.schema_migrations (version, name) values
  ('0001', 'init'),
  ('0002', 'integrations'),
  ('0003', 'accounts'),
  ('0004', 'uploads'),
  ('0005', 'admin'),
  ('0006', 'function_grants'),
  ('0007', 'blockers'),
  ('0008', 'operator_allowlist'),
  ('0009', 'scans')
on conflict (version) do nothing;

commit;

-- ============================================================================
-- BECOMING AN OPERATOR — nothing to do here any more.
--
-- public.admins still has NO client write policy: nothing reachable from a
-- browser can grant console access, including the console itself. What changed
-- is WHERE the grant comes from. 0008 adds public.admin_allowlist, keyed by
-- email, and a trigger on auth.users that promotes a matching CONFIRMED
-- address on first sign-in. It also promotes anyone already signed in, so it
-- is correct whichever order those two things happen in.
--
-- This block used to say "after you have signed into the app once, and not
-- before" and hand you an INSERT to uncomment. That was the chicken-and-egg
-- itself written down as a procedure: admins.user_id references auth.users,
-- the console is what you sign in to, and until you were an operator it showed
-- you nothing.
--
-- To add or remove an operator, edit public.admin_allowlist. It is RLS-on with
-- no policies, so only this editor and the service role can see or change it.
-- ============================================================================

-- Who is on the list, and who has actually been promoted:
-- select a.email, a.role, (u.id is not null) as signed_in_yet
--   from public.admin_allowlist a
--   left join auth.users u on lower(btrim(u.email)) = a.email;
